name: medicine-kit

services:
  db:
    image: postgres:15-alpine
    container_name: medicine_kit_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: medicine_kit
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medicine_kit"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: medicine_kit_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:12345@db:5432/medicine_kit?schema=public
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:3000').then(() => process.exit(0)).catch(() => process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: medicine_kit_web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      HOSTNAME: 0.0.0.0
      API_URL: http://api:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_APP_URL: http://localhost:3001
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3001:3001"

volumes:
  postgres_data:
